services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      VITE_BACKEND_URL: http://localhost:4000
      VITE_BASE_URL: /
      VITE_BROKER_HOST: localhost
      VITE_BROKER_PORT: 8080
      VITE_DATA_TOPIC: wsa
